# Generated by Django 5.2 on 2025-05-25 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='materiagestioncurso',
            name='nota',
        ),
        migrations.AddField(
            model_name='materiagestioncurso',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materias.horario'),
        ),
        migrations.RemoveField(
            model_name='horario',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='gestion',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='materia',
        ),
        migrations.CreateModel(
            name='Dia_Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.dia')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.horario')),
            ],
            options={
                'unique_together': {('dia', 'horario')},
            },
        ),
    ]
