# Generated by Django 5.2.1 on 2025-06-01 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_materiagestioncurso_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiagestioncurso',
            name='horario',
        ),
        migrations.AddField(
            model_name='materiagestioncurso',
            name='dia_horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materias.dia_horario'),
        ),
    ]
