# Generated by Django 5.2.1 on 2025-06-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0004_remove_materiagestioncurso_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiagestioncurso',
            name='dia_horario',
        ),
        migrations.AddField(
            model_name='materiagestioncurso',
            name='dia_horarios',
            field=models.ManyToManyField(blank=True, to='materias.dia_horario'),
        ),
    ]
