# Generated by Django 5.2 on 2025-05-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('prof', 'Profesor'), ('alum', 'Alumno')], max_length=5),
        ),
    ]
