# Generated by Django 5.2.1 on 2025-06-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ci',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
