# Generated by Django 5.2.1 on 2025-06-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
