# Generated by Django 5.2.1 on 2025-06-12 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('prof', 'Profesor'), ('alum', 'Alumno'), ('padre', 'Padre de familia')], max_length=5),
        ),
        migrations.CreateModel(
            name='PadreAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(limit_choices_to={'tipo_usuario': 'alum'}, on_delete=django.db.models.deletion.CASCADE, related_name='padres', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(limit_choices_to={'tipo_usuario': 'padre'}, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('padre', 'alumno')},
            },
        ),
    ]
