# Generated by Django 5.2.1 on 2025-06-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='nota1',
            new_name='decidir',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='nota2',
            new_name='hacer',
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True, default='2025-06-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='saber',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='ser',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
