# Generated by Django 5.2.1 on 2025-05-14 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('materias', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.direccion'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.curso'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.gestion'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.fichainscripcion'),
        ),
        migrations.AddField(
            model_name='materiasinscritasgestion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.curso'),
        ),
        migrations.AddField(
            model_name='materiasinscritasgestion',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.fichainscripcion'),
        ),
        migrations.AddField(
            model_name='materiasinscritasgestion',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.gestion'),
        ),
        migrations.AddField(
            model_name='materiasinscritasgestion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.matricula'),
        ),
        migrations.AddField(
            model_name='materiasinscritasgestion',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.nota'),
        ),
        migrations.AddField(
            model_name='participacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.curso'),
        ),
        migrations.AddField(
            model_name='participacion',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.fichainscripcion'),
        ),
        migrations.AddField(
            model_name='participacion',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.gestion'),
        ),
        migrations.AddField(
            model_name='participacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='materiasinscritasgestion',
            unique_together={('ficha', 'materia', 'curso', 'gestion')},
        ),
    ]
