# Generated by Django 5.2.1 on 2025-06-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_rename_nota1_nota_decidir_rename_nota2_nota_hacer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
